# dev 환경용 Doc Converter 오버레이

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
- ../../base
- service-metrics-nodeport.yaml
patches:
- path: patch-image.yaml
- path: patch-replicas.yaml
- path: patch-resources.yaml
- path: patch-tolerations.yaml
images:
- name: my-app-image
  newName: prl7un/teamproject2app
  newTag: 09305757bce2da280a386bdf0e668ad1f40264ed
