# dev 환경 리소스 요청/제한을 지정한다.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-converter
spec:
  template:
    spec:
      containers:
        - name: doc-converter
          resources:
            requests:
              cpu: 300m
              memory: 768Mi
            limits:
              cpu: 1000m
              memory: 1Gi
