name: CI/CD Pipeline # 이름은 자유롭게 정하셔도 됩니다.

on:
  push:
    branches:
      - '**'
    paths:
      - 'app/doc-converter/**'
      - '.github/workflows/ci.yml'

permissions:
  contents: write # 4번 단계를 위해 반드시 필요합니다.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. 도커 허브 로그인 (본인 계정 시크릿 사용)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. 이미지 빌드 및 본인 레포지토리로 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: app/doc-converter
          file: app/doc-converter/Dockerfile
          push: true 
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/teamproject2app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/teamproject2app:${{ github.sha }}

      # Trivy 취약점 스캔
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.35.0  # 안전이 검증된 최신 버전
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/teamproject2app:${{ github.sha }}'
          trivy-version: '0.69.3' #v를 제외하고 입력
          format: 'table'      # 터미널에서 보기 편한 테이블 형식
          exit-code: '0'       # 심각한 취약점 발견 시 파이프라인 중단 (0은 통과, 1은 중단)
          ignore-unfixed: true # 패치 방법이 없는 취약점은 제외 (실제 해결 가능한 것만 집중)
          severity: 'CRITICAL,HIGH' # 심각(Critical) 및 높음(High) 단계만 체크

      # 3. [추가된 단계] Kustomize로 태그 수정
      - name: Update Kustomize image tag
        run: |
          cd cluster/workloads/apps/doc-converter/overlays/dev
          # 'my-app-image'는 patch-image.yaml에 적힌 이름과 똑같이 맞추세요!
          kustomize edit set image my-app-image=${{ secrets.DOCKERHUB_USERNAME }}/teamproject2app:${{ github.sha }}

      # 4. [추가된 단계] 수정된 kustomization.yaml을 GitHub에 다시 푸시1
      - name: Commit and Push to GitHub
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add cluster/workloads/apps/doc-converter/overlays/dev/kustomization.yaml
          git diff --cached --quiet && exit 0
          git commit -m "chore: update image tag to ${{ github.sha }}"
          git push